### ISSUE TITLE
Incorrect Response Delay values with Macro requests

### ISSUE THREAD

**Issue by v-p-b** [nccgroup/BurpSuiteLoggerPlusPlus#38]
I'm using macros to trigger some "stateful behavior" on my target - this requires multiple requests to be sent in sequence, basically the last one will cause the previous input to be parsed, and trigger the vulnerability. I wrote a quick and dirty Flask script for simulation:

```py
import os
from flask import Flask,request

class BurpTest:
    def __init__(self):
        self.c=""

    def run(self):
        os.system(self.c)

bt=BurpTest()
app=Flask(__name__)

@app.route("/")
def vuln():
    if 'c' in request.args:
        bt.c=request.args['c']
    return "hello"

@app.route("/run")
def r():
    bt.run()
    return "world"
```

As you can see this is a trivial command injection case. This is also detected by Burp that recognizes that some input results in >20s responses. However, the Response Delay values of Logger++ never show anything >1s.

I'm using post-request macros and make the response to the last macro request replace the response delivered to the Scanner.

**Comment by ngregoire** [comment]
This bug isn't specific to macros. Requests going through the Proxy are OK-ish, but requests coming from Repeater have absurd delays (like <1s for delays between 10 and 30 seconds). Tested with v3.07.

**Comment by CoreyD97** [comment]
So I believe the issue here was related to Logger++'s threading. As responses were returned, they're queued for processing to prevent the main thread from hanging but didn't get their response time recorded until the scheduler got to that message. 

I've moved the recording of the response time outside the handling of the scheduler so this should be more true to the actual values though will still be effected by load-order and other environmental factors and differs quite largely from values recorded in Chrome's Network tab for example.

As for messages coming from tools other than the proxy, the issue @ngregoire was seeing was due to the inability to match requests with responses passed by burp. With messages coming from the proxy, these contain a parameter to identify the request/response pair which is not present for other tools.

As a workaround, Logger++ will now use the comment field to tag messages from other tools with a UUID to be able to match requests and responses. (It is possible that other extensions utilising the comment field may break this functionality dependent on load order, though Logger++ will only add to the comment, not replace it in it's entirety).

With this implemented, requests from other tools should now correctly reflect the delay between request/response. (Though do account for environmental factors!)
