### ISSUE TITLE
Bug at Log Method on Toggle

### ISSUE THREAD

**Issue by arbazkiraak** [nccgroup/BurpSuiteLoggerPlusPlus#70]
Hi @CoreyD97 ,

There's a tiny bug at logger plug, which shows the `Orginal` Method of the request on log table but content would be `POST`.

> Reproduce.

1. Intercept the request.
2. Toggle the request from GET to POST or vice-versa.
3. Check the Logger++ logs table.

**Comment by CoreyD97** [comment]
Hey, sorry but I think this is actually caused by the way which the Burp API works.
Burp passes the request to the extension before burp itself handles the requests so any modifications made after the extension processes the request/response.

I have an idea on how this might be implemented. I'll give it a try and see if it is possible.
